# Generated by Django 5.0.1 on 2024-01-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Comment', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='hamper_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamper_category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('dp', models.ImageField(upload_to='photos')),
                ('Dob', models.DateField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='hamper_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamper_name', models.CharField(max_length=200)),
                ('hamper_price', models.IntegerField()),
                ('hamper_image', models.ImageField(upload_to='photos')),
                ('cat_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.hamper_category')),
                ('vendor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='hamper_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMENT', models.CharField(default='', max_length=300)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Hamper_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.hamper_details')),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='hamper_category',
            name='L_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.CreateModel(
            name='FEEDBACK_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATINGS', models.CharField(max_length=300)),
                ('COMMENT', models.CharField(default='', max_length=300)),
                ('L_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=25)),
                ('Pro_image', models.ImageField(upload_to='photos')),
                ('Pro_description', models.TextField()),
                ('Pro_price', models.IntegerField()),
                ('Pro_Cat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_category')),
                ('vendor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Hamper_charge', models.IntegerField(default=0)),
                ('Final_price', models.IntegerField()),
                ('Order_id', models.IntegerField(default=0)),
                ('Order_status', models.IntegerField(default=0)),
                ('Hamper_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.hamper_details')),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
                ('Product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=35)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Placed', 'Placed')], max_length=50)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
