# Generated by Django 5.0.1 on 2024-01-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_cart_hamper_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='login_table',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login_table',
            name='usertype',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('User', 'User')], default='', max_length=100),
        ),
    ]
