# Generated by Django 5.0.1 on 2024-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_login_table_comments_login_table_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='Cat_image',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
