# Generated by Django 5.0.1 on 2024-01-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamper_details',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='hamper_category',
        ),
    ]
