# Generated by Django 4.2.3 on 2024-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='rev_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
