from django.urls import path, include
from . import views

urlpatterns = [
   path("", views.index, name="index"),
   path("signup", views.signup, name="signup"),
   path("login", views.login, name="login"),
   path("logout", views.logout, name="logout"),
   path("forgot", views.forgot, name="forgot"),
   path("forgotpassword", views.forgotpassword, name="forgotpassword"),
   path("profile", views.profile, name="profile"),
   path("editprofile", views.editprofile, name="editprofile"),
   path("updateprofile", views.updateprofile, name="updateprofile"),
   path("editpw", views.editpw, name="editpw"),
   path("updatepw", views.updatepw, name="updatepw"),
   path("addproducthamper", views.addproducthamper, name="addproducthamper"),
   path("addproduct", views.addproduct, name="addproduct"),
   path("addhamper", views.addhamper, name="addhamper"),
   path("manageproduct", views.manageproduct, name="manageproduct"),
   path("managehamper", views.managehamper, name="managehamper"),
   path("removeproduct/<int:rpid>", views.removeproduct, name="removeproduct"),
   path("removehamper/<int:rhid>", views.removehamper, name="removehamper"),
   path("catwiseprods/<int:cwpid>", views.catwiseprods, name="catwiseprods"),
   path("proddetails/<int:pdid>", views.proddetails, name="proddetails"),
   path("removefromcart/<int:rcid>", views.removefromcart, name="removefromcart"),
   path("yourordersingle/<int:yoid>", views.yourordersingle, name="yourordersingle"),
   path("allcats", views.allcats, name="allcats"),
   path("myorders", views.myorders, name="myorders"),
   path("vendororders", views.vendororders, name="vendororders"),
   path("addtocart", views.addtocart, name="addtocart"),
   path("mycart", views.mycart, name="mycart"),
   path("checkout", views.checkout, name="checkout"),
   path("allprods", views.allprods, name="allprods"),
   path("contact", views.contactus, name="contact"),
   path("contactwithus", views.contactwithus, name="contactwithus"),
   path("about", views.about, name="about"),
   path("viewdata", views.viewdata, name="viewdata"),
   path("searchresult", views.searchresult, name="searchresult"),
   path("hamperfeedback", views.hamperfeedback, name="hamperfeedback"),
   path("checkuser", views.checklogin, name="checkuser"),
   path("placeorder", views.placeorder, name="placeorder"),
   path("vendororders", views.vendororders, name="vendororders"),
   path("hamperorders", views.hamperorders, name="hamperorders"),
   path("placeorders", views.placeorders, name="placeorders"),
   path("submitreview", views.SubmitReview, name="submitreview"),
   path("submitProdRating/<int:p_id>", views.Review, name="submit_rate")
]